version = 4
final_space = true
async = true

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "p:text-light"
  background = "#5A6269"
  template = "{{ .Path }} "
  powerline_symbol = "=>"

	[blocks.segments.properties]
		style = "full"

  [[blocks.segments]]
  type = "git"
  alignment = "right"
  style = "plain"
  foreground = "p:text-light"
  background = "#5A6269"
  template = "{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Staging.Changed) (.Working.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} "
  powerline_symbol = "=>"

    [blocks.segments.cache]
    duration = "2s"
    strategy = "session"

  [[blocks.segments]]
  type = "project"
  style = "plain"
  foreground = "p:text-light"
  background = "#5A6269"
  template = "  {{ .Name }}{{ if .Version }} {{ .Version }}{{ end }} "
  powerline_symbol = "=>"

  [[blocks.segments]]
  type = "os"
  style = "plain"
  powerline_symbol = "=>"
  template = " {{ if .WSL }}WSL at {{ end }}{{.Icon}} "
  foreground = "p:text-light"
  background = "#5A6269"

    [blocks.segments.cache]
    duration = "24h"
    strategy = "session"

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "p:text-light"
  template = "❯"

[transient_prompt]
foreground="p:text-light"
template = "❯ "
