# ~/.config/alacritty/alacritty.toml
[env]
TERM = "screen-256color"

[terminal.shell]
program = "/usr/bin/zsh"

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Italic" }
bold_italic = { family = "Fira Code", style = "Bold Italic" }
size = 16

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullScreen"

[colors.primary]
background = "#000000"
# background = "#f5f5f5"
