# ~/.config/alacritty/alacritty.toml

[terminal.shell]
program = "/usr/bin/zsh"

[font]
normal = { family = "Jetbrains Mono", style = "Regular" }
bold = { family = "Jetbrains Mono", style = "Bold" }
italic = { family = "Jetbrains Mono", style = "Italic" }
bold_italic = { family = "Jetbrains Mono", style = "Bold Italic" }
size = 16


[[keyboard.bindings]]
key = "F11"
action = "ToggleFullScreen"

# [colors.primary]
# background = "#000000"
