theme = "carbonfox"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
continue-comments = false
completion-replace = true
bufferline = "multiple"
trim-trailing-whitespace = true
popup-border = "all"

[editor.statusline]
left = ["mode", "spinner", "read-only-indicator", "file-modification-indicator"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.insert = ""
mode.normal = ""
mode.select = "󰒅"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.lsp]
display-messages = true
display-progress-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "none"
nnbsp = "none"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "warning"

[keys.normal]
C-o = ":config-open"
C-r = ":config-reload"
C-d = ["align_view_center", "page_cursor_half_down"]
C-u = ["align_view_center", "page_cursor_half_up"]
esc = ["collapse_selection", "keep_primary_selection"]
tab = ":buffer-next"
S-tab = ":buffer-previous"

[keys.insert]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
